name: build-and-test
on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 0,15 * * *'

env:
  CODE_COVERAGE: true
  LCOV: true

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [ 2.5.0, 3.2.0 ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.version }}

      - name: Install dependencies
        run: |
          bundle config set --local without 'rubocop'
          bundle install

      # If you add a new dependency, be sure to run `bundle exec srb rbi update`
      - name: Typecheck
        run: bundle exec srb tc

      - name: Run tests
        run: rake test
        env:
          test_api_key: ${{ secrets.SDK_CONSISTENCY_TEST_COMPANY_API_KEY }}
          test_client_key: ${{ secrets.KONG_CLIENT_SDK_KEY }}

      - name: Run tests in parallel
        run: bundle exec rake parallel:test
        env:
          test_api_key: ${{ secrets.SDK_CONSISTENCY_TEST_COMPANY_API_KEY }}
          test_client_key: ${{ secrets.KONG_CLIENT_SDK_KEY }}

      - name: Add code coverage comment
        uses: romeovs/lcov-reporter-action@v0.2.16
        with:
          lcov-file: ./coverage/lcov/ruby-sdk.lcov
          github-token: ${{ secrets.GITHUB_TOKEN }}
